package de.feu.massim22.group3.agents.events;

public enum EventName {
    UPDATE,
    TO_SUPERVISOR,
    FROM_SUPERVISOR,
    MAP_SENT_TO_NAVI,
    PATHFINDER_RESULT,
    MERGE_SUGGESTION,
    UPDATE_GROUP,
    ADD_GROUP_MEMBERS,
    REPORT_POSSIBLE_CONNECTION,
    SUPERVISOR_PERCEPT_DELIVER_BLOCK,
    SUPERVISOR_PERCEPT_DELIVER_BLOCK_DONE,
    SUPERVISOR_PERCEPT_RECEIVE_BLOCK,
    SUPERVISOR_PERCEPT_DELIVER_TWO_BLOCK,
    SUPERVISOR_PERCEPT_RECEIVE_TWO_BLOCK,
    SUPERVISOR_PERCEPT_GET_BLOCK,
    SUPERVISOR_PERCEPT_CANCELED,
    SUPERVISOR_PERCEPT_DONE_OR_CANCELED,
    PERCEPT_MEET_AT,
    ATTACH_REPLY,

}
